### ISSUE TITLE
After first run on job creation, update fails

### ISSUE THREAD

**Issue by sudoFerraz** [maxam2017/productive-box#1]
Run maxam2017/productive-box@v1.0.0
(node:2605) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'login' of undefined
    at /home/runner/work/_actions/maxam2017/productive-box/v1.0.0/dist/index.js:1:21789
    at step (/home/runner/work/_actions/maxam2017/productive-box/v1.0.0/dist/index.js:1:20946)
    at Object.next (/home/runner/work/_actions/maxam2017/productive-box/v1.0.0/dist/index.js:1:20231)
    at fulfilled (/home/runner/work/_actions/maxam2017/productive-box/v1.0.0/dist/index.js:1:19731)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2605) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2605) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by maxam2017** [comment]
Thanks for your report.
I watched the configuration of your GitHub workflows and found it lacks the environment variables field.
> more info: https://github.com/maxam2017/productive-box/blob/master/.github/workflows/schedule.yml#L15-L18

**Comment by sudoFerraz** [comment]
Thank you 👍

**Comment by sudoFerraz** [comment]
Hmm, I think you might have looked wrongly, please check it again: https://github.com/sudoFerraz/productive-box/actions/runs/83428960/workflow

**Comment by maxam2017** [comment]
> Hmm, I think you might have looked wrongly, please check it again: https://github.com/sudoFerraz/productive-box/actions/runs/83428960/workflow

It seems strange. Can you describe this issue in more detail 🙏 
I use the same config as you but it works.

<details>
<summary> my config </summary>

```
name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: e789d0832261226fe96c4dc3d12156ad
          LOCALE: zh-TW
```

</details>
